---
prefilter:
  data: /Users/lucamicheletti/cernbox/JPSI/Jpsi_flow/data/pass3/LHC23_full/minitree/train_262043/AO2D.root
  treeIn: "DF_2338657048853728/O2rtdileptmtree"
  treeOut: "minitree_Centr_30_50__Pt_12_15"
  cuts: "(fCentFT0C >= 30. && fCentFT0C < 50. && fPt > 12. && fPt < 15. && fCos2DeltaPhi > -1. && fCos2DeltaPhi < 1.)"
  suffix: _Centr_30_50__Pt_12_15