
input:
    output_dir_name: "/Users/lucamicheletti/cernbox/JPSI/Jpsi_flow/data/pass2/LHC22zzh/"
    run_list: [
      544124,
      544123,
      544122,
      544121,
      544116,
      544098,
      544095,
      544091
    ]

    alien_input_path: [
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306028/AOD",
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306027/AOD",
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306026/AOD",
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306025/AOD",
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306024/AOD",
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306023/AOD",
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306022/AOD",
      "/alice/cern.ch/user/a/alihyperloop/jobs/0030/hy_306021/AOD"
    ]

    file_type: "AnalysisResults.root"
    file_path: "/Users/lucamicheletti/cernbox/JPSI/Jpsi_flow/data/pass2/LHC22zzh/"
    table_maker_stat: table-maker/Statistics
    table_maker: table-maker/output
    table_maker_dir: ["Muons_muonQualityCuts"]
    table_maker_obj: ["Pt"]

output:
    output_fig_name: figures_1/LHC22o_full_stat
    output_dir_name: /Users/lucamicheletti/cernbox/JPSI/Jpsi_flow/data/pass2/LHC22zzh/
    output_file_name: AO2D_reduced_with_flow.root
